apiVersion: v1
kind: Service
metadata:
  name: contosoworkflow2
  namespace: namespace-workflow-1679337123260
spec:
  type: LoadBalancer
  selector:
    app: contosoworkflow2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000